[package]
name = "fixed_math"
description = "Mathematic functions for `fixed` numbers."
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
default = []
std = ["fixed/std"]

[dependencies]
fixed = { path = "../fixed" }
# fixed = { git = "https://gitlab.com/tspiteri/fixed.git", branch = "v1" }
