[package]
name = "fixed_math"
description = "Some math functions for `fixed` point numbers."
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace]
members = ["tablegen"]

[features]
default = []
std = ["fixed/std"]

[dependencies]
fixed = { path = "../fixed" }
typenum = "1.15.0"

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "sin_cos"
harness = false
