[package]
name = "fixed_math"
description = "Some math functions for `fixed` point numbers."
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
default = []
std = ["fixed/std"]

[dependencies]
fixed = { path = "../fixed" }
# fixed = { git = "https://gitlab.com/tspiteri/fixed.git", rev = "12982db6" }
seq-macro = { version = "0.3.1" }
